openapi: 3.0.3
info:
  title: Custom API
  version: 1.0.0
paths:
  /labseq/{n}:
    get:
      summary: Calculate the sequence value
      parameters:
        - in: path
          name: n
          required: true
          description: The non-negative integer index
          schema:
            type: integer
      responses:
        '200':
          description: The sequence value
          content:
            application/json:
              schema:
                type: number
        '400':
          description: Bad request. Index must be a non-negative integer
          content:
            application/json:
              schema:
                type: string